### ISSUE TITLE
CrossOver not taking controller input after patch

### ISSUE THREAD

**Issue by AnonyMeXx** [italomandara/CXPatcher#112]
Hello,
After applying the patch, CrossOver 22.1.1 shows "Controller (Xbox One For Windows)" under 'Connected (xinput device)' but I cannot test the controller and I can't play with it. I removed the patched app and installed CrossOver again and I was able to successfully test the controller so I'm pretty sure it has something to do with the patch.

Any help is appreciated!

**Comment by italomandara** [comment]
We don't patch anything related to controllers and I'm pretty sure it's not cxpatcher using this.
I did some investigation on this and this is what I've found out:
If you have your controller connected and you have the Mac Steam app running in the background it will take over the controller and creates a new device for it:

<img width="389" alt="Screenshot 2023-08-29 at 18 47 24" src="https://github.com/italomandara/CXPatcher/assets/12135454/630a5824-e337-4cc6-b758-ce6d1126b8e2">

in my case the name is different probably because I have a DS4 gamepad.

if I close the Mac steam app that device then disappears:
<img width="387" alt="Screenshot 2023-08-29 at 18 47 55" src="https://github.com/italomandara/CXPatcher/assets/12135454/9fdca342-6198-47ea-9281-55f4616a9e6c">

So I think you left Steam for Mac open in the background by mistake, so make sure that you don't have Steam for Mac open in the background.

If that's not the case I can't really fix that but I suggest to set "Controller (Xbox One For Windows)" to "override" and then to "disable"

**Comment by AnonyMeXx** [comment]
I opened Activity Monitor and searched for Steam to see if anything's running in the background but it isn't, and I never have Steam open because I've seen threads of people who said that Steam assigns and remaps controllers for you ...etc. I also tried the override and disable and that didn't work either.
I guess I'll have to wait until v0.4 with the CrossOver 23 update and see then. Thank you for your amazing work!

**Comment by italomandara** [comment]
> I opened Activity Monitor and searched for Steam to see if anything's running in the background but it isn't, and I never have Steam open because I've seen threads of people who said that Steam assigns and remaps controllers for you ...etc. I also tried the override and disable and that didn't work either. I guess I'll have to wait until v0.4 with the CrossOver 23 update and see then. Thank you for your amazing work!

Another hint: disable steam input on the wine steam client

**Comment by AnonyMeXx** [comment]
Okay I did some more testing, and when I open "Game Controller" under "Control Panels" the first time, it registers my device. But after I test it and close the window, I think it keeps a certain task in the background that somehow takes the input from my controller to it and doesn't allow me to use it for games. And when I quit CrossOver, it gives me this popup ONLY IF I open "Game Controller":
![Screenshot 2023-08-29 at 23 23 29](https://github.com/italomandara/CXPatcher/assets/45255579/f832c163-d0a1-460c-846a-44c56607419f)
Also, I noticed when I turn CrossOver on and then turn on my controller, it takes registers input during testing; when I have it on and then turn on CrossOver, it doesn't register any input at all. This is weird behavior but I would guess maybe it has something to do with macOS Sonoma and it being in beta and all. 

Thanks for your input anyways and again thanks for this project!

**Comment by italomandara** [comment]
> Okay I did some more testing, and when I open "Game Controller" under "Control Panels" the first time, it registers my device. But after I test it and close the window, I think it keeps a certain task in the background that somehow takes the input from my controller to it and doesn't allow me to use it for games. And when I quit CrossOver, it gives me this popup ONLY IF I open "Game Controller": ![Screenshot 2023-08-29 at 23 23 29](https://user-images.githubusercontent.com/45255579/264148259-f832c163-d0a1-460c-846a-44c56607419f.png) Also, I noticed when I turn CrossOver on and then turn on my controller, it takes registers input during testing; when I have it on and then turn on CrossOver, it doesn't register any input at all. This is weird behavior but I would guess maybe it has something to do with macOS Sonoma and it being in beta and all.
> 
> Thanks for your input anyways and again thanks for this project!

no worries, unfortunately I can't replicate that issue with my ds4
