### ISSUE TITLE
Make CXPatcher have a separate bottles path

### ISSUE THREAD

**Issue by italomandara** [italomandara/CXPatcher#114]
https://www.codeweavers.com/support/wiki/mac/faq/cxofficemacbottlelocation

Maybe append it so it’s CXPatcher_Bottles

This would mean it would be possible to have bottles just for CXPatcher CrossOver and the default for stock CrossOver
This could be made optional but defaulting to have their feature enabled.

**Comment by MysticalOS** [comment]
This would be nice yeah. I literally can't use crossover 23 for testing cause i don't want it messing up my bottles.I did read it's possible to have diff copies of app have diff bottles by modifying the app bundles hard coded bottle location but i haven't done it quite yet.

if you add that modification to patcher though then you may want to do it in a way that if you've already changed bottle location, you read that changed path first THEN add CXPatcher_ to it. for example i globally changed my bottles to external nvme drive. Alternatively, just let user physically choose new bottle location instead of just changing it.

**Comment by MysticalOS** [comment]
https://www.codeweavers.com/support/wiki/mac/faq/cxofficemacbottlelocation is faq i was researching on

**Comment by MysticalOS** [comment]
![Screenshot 2023-09-01 at 10 16 33 AM](https://github.com/italomandara/CXPatcher/assets/1899149/79bb0c2e-3d7f-48f2-9eb0-8facc45d86d2)
But you know what, i'm gonna go ahead and just finally hard code this in mine since I already know how from faq. then finally install crossover 23 for tinkering with diff bottles :D

**Comment by italomandara** [comment]
> This would be nice yeah. I literally can't use crossover 23 for testing cause i don't want it messing up my bottles.I did read it's possible to have diff copies of app have diff bottles by modifying the app bundles hard coded bottle location but i haven't done it quite yet.
> 
> if you add that modification to patcher though then you may want to do it in a way that if you've already changed bottle location, you read that changed path first THEN add CXPatcher_ to it. for example i globally changed my bottles to external nvme drive. Alternatively, just let user physically choose new bottle location instead of just changing it.

I'm tempted to do that but given most of the issue after patching crossover are caused by the old bottle that gets messy, I would force the user to create a fresh bottle after patch. @Gcenx What's your view on this?

**Comment by MysticalOS** [comment]
for sure, they should use separate bottles. my only feedback is don't just tells us where it should be, I need mine on an external volume. so it should still let me choose WHERE it goes.

**Comment by italomandara** [comment]
it will be optional anyway so if you want to keep the bottles you can turn that off in the patcher options

**Comment by italomandara** [comment]
implemented in https://github.com/italomandara/CXPatcher/pull/125

**Comment by italomandara** [comment]
Implemented in https://github.com/italomandara/CXPatcher/pull/125
