### ISSUE TITLE
Add possibility to customize the CXPatcher bottle path

### ISSUE THREAD

**Issue by italomandara** [italomandara/CXPatcher#139]

**Comment by MysticalOS** [comment]
100% yes. I was already looking into maybe using a sym link to redirect CXBottle from users to my external when I saw where you default the path for that. that's primary reason I need custom path. on a macbook pro i only have finite amount of storage but I have 2TB NVMe external via thunderbolt that has my bottles.

An also smart thing to do would be to default read external pref for default location (if it's been changed) then make modified location CXBOTTLE in that location too, but visible you did this because the new UI would show an exit box for custom bottle path. so you import the default default path if user has no alterations, or you import the user altered path + CX and it's always visible from a UX perspective on what's been done where whether user types over exit box with custom or not.

**Comment by hwamil** [comment]
1. Create bottle
2. Move bottle to another location (server, external storage, etc.)
3. `ln -s 'BottlePath' '/Users/{username}/CXBottles'`

**Comment by simonsax** [comment]
It would be great to be able to define the default path for CXPatcher similar to crossover
`defaults write com.codeweavers.CrossOver BottleDir <path>`

Unfortunately the above mentioned method with the `ln -s 'SSD/CXPBottles' '/Users/XYZ/CXPBottles'` didn't work for me -> crossover does not launch with `/Users/XYZ/CXPBottles`  pointing to `SSD/CXPBottles`

**Comment by italomandara** [comment]
the work on this branch will be much user friendly than a command in the terminal.
