### ISSUE TITLE
Not loading installed GStreamer

### ISSUE THREAD

**Issue by plbstl** [italomandara/CXPatcher#55]
v0.2.16

I have GStreamer installed through pkg downloaded from its official website. But CXPatcher still asks to install GStreamer.

<img width="512" alt="Screenshot 2023-07-11 at 10 36 56" src="https://github.com/italomandara/CXPatcher/assets/49006567/0cc16625-8bd2-453e-86cd-ad626a3612a0">

<img width="522" alt="Screenshot 2023-07-11 at 10 39 37" src="https://github.com/italomandara/CXPatcher/assets/49006567/8658d25e-d80e-4bb8-b8b1-3ca3ef9a3bdf">

**Comment by plbstl** [comment]
I'm on Ventura. Does it matter that I'm not on Sonoma?

**Comment by italomandara** [comment]
If you read it's not telling you're missing gstreamer, it just suggest you to do it, just ignore it and proceed paatching

**Comment by italomandara** [comment]
Nonetheless, I'll add something that checks if it's installed when you launch CXPatcher. 

CXPatcher is in no way connected to the GStreamer installer so it doesn't know if you're installing GStreamer while it's open, I know how to monitor file changes and check for GStreamer installation, but it's an overkill tbh. Since that warning it's just meaning "Install GStreamer if you haven't done it yet"

**Comment by italomandara** [comment]
In the next release CXPatcher Will check for GStreamer Installation and show a green checkmark in the next release.
