### ISSUE TITLE
OW2 not launching anymore

### ISSUE THREAD

**Issue by nahasco** [italomandara/CXPatcher#61]
I have been playing Overwatch 2 on my Mac thanks to CXpatcher, crossover, and GPTK for the past couple weeks with perfect 100fps+. Unfortunately I am not able to launch the game anymore. Not sure you it just crashes on launch. Can someone confirm this? What's going wrong here?

**Comment by MysticalOS** [comment]
They changed it to now not include one of files GTPk kinda needs for some games. I'm not sure it was a good change, ironically it was done specifically for overwatch 2 to function correctly when using DXVK, but it breaks it working correctly (or mostly correctedly) when using D3DMetal and I worry what other situations it may break. But I was also under impression D3DMetal and OW2 resulted in pretty bad stuttering and other quirks which is why people favored using DXVK instead (with the specific GTPk file reverted). So maybe try playing that way instead?

But yeah, I still worry what reverting that file might do for other applications. Apple modified it for a reason for D3DMetal

**Comment by nahasco** [comment]
> They changed it to now not include one of files GTPk kinda needs for some games. I'm not sure it was a good change, ironically it was done specifically for overwatch 2 to function correctly when using DXVK, but it breaks it working correctly (or mostly correctedly) when using D3DMetal and I worry what other situations it may break. But I was also under impression D3DMetal and OW2 resulted in pretty bad stuttering and other quirks which is why people favored using DXVK instead (with the specific GTPk file reverted). So maybe try playing that way instead?
> 
> But yeah, I still worry what reverting that file might do for other applications. Apple modified it for a reason for D3DMetal

I did revert that file after creating a copy to Crossover so the change only affected the copy. But now it doesn't work anymore the game just crashes on launch. Am I the only one facing this issue?

**Comment by italomandara** [comment]
can you provide the cxlog? is there an error window or does it just crash without error?

**Comment by italomandara** [comment]
This is fixed by patching crossover without gptk
